[package]
name = "lab4"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-stream = "0.1"